export const REPORT_TYPES = {
    FINANCIAL: 'FINANCIAL',
    INVENTORY: 'INVENTORY',
    MECHANIC: 'MECHANIC',
    CUSTOMER: 'CUSTOMER'
};

export const EXPORT_FORMATS = {
    JSON: 'JSON',
    PDF: 'PDF',
    CSV: 'CSV',
    EXCEL: 'EXCEL'
};

export const TIME_PERIODS = {
    DAILY: 'DAILY',
    WEEKLY: 'WEEKLY',
    MONTHLY: 'MONTHLY',
    QUARTERLY: 'QUARTERLY',
    YEARLY: 'YEARLY',
    CUSTOM: 'CUSTOM'
};